name: Deploy to Render

on:
    push:
        branches:
            - main # trigger deployment on the main branch
        
jobs:
    render-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Trigger Render Deploy Hook
              run: |
                curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}